# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Carson's Meditations
email: ctkfdp@umsystem.edu
description: >- # this means to ignore newlines until "baseurl:"
  My site for my reflections on all types of projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carsontkempf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "carsontkempf/carsontkempf.github.io"
github_username:  carsontkempf
author: Carson Kempf

safe: false
show_downloads: false
google_analytics: "G-DSMK52452T"
theme: jekyll-theme-minimal
sass:
  sass_dir: _sass

# Spotify API Configuration
spotify:
  client_id: "80826ef3daa547f49d843c254ad224b6"

# Auth0 Configuration (production - gh-pages branch)
auth0:
  domain: "dev-l57dcpkhob0u7ykb.us.auth0.com"
  client_id: "Dq4tBsHjgcIGbXkVU8PPvjAq3WYmnSBC"
  audience: "https://carsontkempf.github.io/api/carsons-meditations"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor